app/main/models.py
from app import db


class MediaMixin(object):

    def __repr__(self):
        return '<{} {}>'.format(self.__class__.__name__, self.title)


class Paper(MediaMixin, db.Model):

    id = db.Column(db.Integer, primary_key=True)
    content_path = db.Column(db.Text)
    title = db.Column(db.Text, index=True)
    abstract = db.Column(db.Text)
    coauthors = db.Column(db.Text, index=True)


class Project(MediaMixin, db.Model):

    id = db.Column(db.Integer, primary_key=True)
    content_path = db.Column(db.Text)
    title = db.Column(db.Text, index=True)
    abstract = db.Column(db.Text())
    coauthors = db.Column(db.Text(), index=True)


class Photograph(MediaMixin, db.Model):

    id = db.Column(db.Integer, primary_key=True)
    content_path = db.Column(db.String(64))
    title = db.Column(db.String(64), index=True)
    subject = db.Column(db.String(64), index=True)  # e.g. 'Pub' or 'Glasgow'
    painting = db.relationship('Painting', backref='photograph', lazy='dynamic')

    def modal_images(self):
        """
        The images which dynamically appear when we click on the base image
        """
        return [self.content_path]


class Painting(MediaMixin, db.Model):

    id = db.Column(db.Integer, primary_key=True)
    content_path = db.Column(db.String(64))
    title = db.Column(db.String(64), index=True)
    subject = db.Column(db.String(64), index=True)
    photo_id = db.Column(db.Integer, db.ForeignKey('photograph.id'))

    def modal_images(self):
        """
        The images which dynamically appear when we click on the base image
        """
        return [self.content_path, self.photograph.content_path]

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

# Flask uses the location of the module passed here as a starting point when
# it needs to load associated resources such as template files.
db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)

    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    return app

from app.main import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp as main_bp
from app.main.models import Painting, Paper, Photograph, Project
from app.static.publications_config import publications_title_to_data
from app.static.projects_config import project_title_to_data

from flask import render_template, url_for

from collections import namedtuple

Link = namedtuple('Link', ['link', 'display'])


@main_bp.route('/')
@main_bp.route('/home')
def home():
    links = [Link(link='main.projects', display='Projects'), Link('main.publications', display='Publications'),
             Link(link='main.gallery_front', display='Gallery')]
    return render_template('home.html', links=links, central_image="static/anderstonFootbridge.jpg")


@main_bp.route('/about')
def about():
    local_links = [Link(link='main.projects', display='Projects')]
    web_links = [Link(link='https://www.linkedin.com/in/paul-gilmartin/', display='LinkedIn'),
                 Link(link='static/Professional_CV.pdf', display='C.V.'),]
    return render_template('about.html', local_links=local_links, web_links=web_links)


@main_bp.route('/contact')
def contact():
    return render_template('contact.html')


@main_bp.route('/publications')
def publications():
    papers = Paper.query.all()
    blurb = """My research interests lie primarily in the field of non-commutative algebra. I'm particularly interested in
             Hopf algebras of finite GK-dimension, quantum groups, quantum homogeneous spaces
             and Poisson algebraic groups. My published research papers in this field are listed below."""

    # TODO: in the below we pass a paper_config variable in to avoid having to include long text data
    # since I can't currently find a way to upload a record with such properties to mysql in the prod db
    # To find a way to fix this and eliminate need for hard-coded publication data in the static file
    return render_template('/publications.html', blurb=blurb, papers=papers,
                           paper_config=publications_title_to_data, title='Publications')


@main_bp.route('/projects')
def projects():
    projs = Project.query.all()
    blurb = """This page details some of the programming projects I've worked on in my spare time. More to come
    in the not too distant future."""
    return render_template('/projects.html', paper_config=project_title_to_data,
                            papers=projs, blurb=blurb, title='Projects')


@main_bp.route('/gallery')
def gallery_front():
    links = [Link('main.glasgow', display='Glasgow'), Link(link='main.pubs', display='Pubs'),
             Link(link='main.paintings', display='Paintings')]
    return render_template('/gallery/gallery_front.html', links=links,
                           central_image="../static/maryhill.jpg")


@main_bp.route('/gallery/pubs')
def pubs():
    photos = Photograph.query.filter_by(subject='Pub').all()
    return render_template('/gallery/pubs.html', photos=photos, title='Pubs')


@main_bp.route('/gallery/glasgow')
def glasgow():
    photos = Photograph.query.filter_by(subject='Glasgow').all()
    return render_template('/gallery/glasgow.html', photos=photos, title='Glasgow')


@main_bp.route('/gallery/paintings')
def paintings():
    paintings = Painting.query.all()
    return render_template('/gallery/paintings.html', photos=paintings, title='Paintings')

app/templates/about.html
{% extends 'base.html' %}

{% block site_content %}

  {% block styles %}
    <!-- Custom styles for this template -->
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="static/custom_about_responsive.css"/>
    <link rel="stylesheet" type="text/css" href="static/custom_home_responsive.css"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=UnifrakturMaguntia" />
  {% endblock %}
<body>

  <div class="container">
      <h1 class="justify-content-center">About</h1>
      <div class="row">
          <div class="col-xs-10 col-lg-6 justify-content-center flex-first portrait">
            <img class="portrait" src="static/self_portrait.jpg"/>
          </div>
          <div class="col-xs-10 col-lg-6 justify-content-center flex-last about">
              My original training is in mathematics, the subject in which I completed a PhD at the University of Glasgow
              in 2016 (you can view my published research papers <a href="{{ url_for('main.publications') }}">here</a>). In the final
              year of my PhD I taught myself how to code and as a result my primary interest transitioned from mathematics
              to programming and computer science. I've now been a professional Python developer for two years. Recently I've developed an interest
                in natural language processing and have been working on a mini <a href="">project</a> in my spare time
                in an attempt to learn more about it.
                <div class="row">
                    {% for link in local_links %}
                        <a class="col-xs-12 col-lg-4 justify-content-left centralLinks flex-last"
                           href="{{ url_for( link.link ) }}">{{ link.display }}</a>
                    {% endfor %}
                    {% for link in web_links %}
                        <a class="col-xs-12 col-lg-4 justify-content-left centralLinks flex-last"
                           href="{{ link.link }}">{{ link.display }}</a>
                    {% endfor %}
                </div>
          </div>
      </div>
  </div>
</body>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<head>
  {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
      {% block title %}
        {{ title }}
      {% endblock title %}
    </title>
    {% block styles %}
      <!-- Bootstrap core CSS -->
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
      <link rel="stylesheet" type="text/css" href="static/custom_base_responsive.css"/>
      <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=UnifrakturMaguntia" />

    {% endblock styles %}
{% endblock head %}
</head>

<body>
  {% block body %}
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light mb-4">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.home') }}">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.contact') }}">Contact</a>
          </li>
        </ul>
      </div>
          <h3>Paul Gilmartin</h3>
    </nav>
    {% endblock navbar %}
    {% block content %}
      {% block site_content %}
      {% endblock %}
    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  {% endblock body %}
</body>

app/templates/contact.html
{% extends 'base.html' %}

{% block site_content %}

  {% block styles %}
    <!-- Custom styles for this template -->
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="static/custom_contact_responsive.css"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=UnifrakturMaguntia" />

  {% endblock %}
  <body>
    <div class="container">
        <div class="row justify-content-center">
            <p class="contactinfo toplink"><b>Email</b>: paul.gilmartin89@gmail.com</p>
        </div>
        <div class="row justify-content-center">
            <p class="contactinfo"><b>Phone</b>: +44 (0) 7506587048</p>
        </div>
        <div class="row justify-content-center">
            <a  class="contactinfo" href="https://www.linkedin.com/in/paul-gilmartin/">LinkedIn</a>
        </div>

    </div>
  </body>

{% endblock %}

app/templates/gallery/gallery_base.html
{% extends 'base.html' %}

{% block site_content %}
  {% block styles %}
    {{ super() }}
    <!-- Custom styles for this template -->
    <link href="../static/custom_gallery_responsive.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../static/custom_base_responsive.css"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=UnifrakturMaguntia" />

  {% endblock %}
  <body>
    <h1>{{ title }}</h1>

    <!-- Default gallery display/ Bootstrap grid system -->
        <div class="container">
            {% for photo in photos %}
          <div class="row justify-content-center">
            <img class="col-xs-6 baseImage" src="{{ photo.content_path }}"
                 data-toggle="modal" data-target="#{{ photo.id }}">
          </div>
          <div class="row justify-content-center">
            <div class="caption">{{ photo.title }}</div>
          </div>​
            {% endfor %}
        </div>

  <!-- Corresponding modal images for each picture displayed -->
    {% for photo in photos %}
     <div class="modal fade" id="{{ photo.id }}" tabindex="-1" role="dialog"
          aria-labelledby="enlargeImageModal" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-body">
                {% for modal_image_path in photo.modal_images() %}
                <img src="{{ modal_image_path }}" class="enlargeImageModalSource" style="width: 100%;">
                {% endfor %}
            </div>
          </div>
        </div>
    </div>
    {% endfor %}

  </body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}

app/templates/gallery/gallery_front.html
{% extends 'home.html' %}

app/templates/gallery/glasgow.html
{% extends 'gallery/gallery_base.html' %}

app/templates/gallery/paintings.html
{% extends 'gallery/gallery_base.html' %}

app/templates/gallery/pubs.html
{% extends 'gallery/gallery_base.html' %}

app/templates/home.html
{% extends 'base.html' %}

{% block site_content %}

  {% block styles %}
    <!-- Custom styles for this template -->
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="static/custome_home_responsive.css"/>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=UnifrakturMaguntia" />

  {% endblock %}
  <body class="homeBody">
    <div class="container">
        <div class="row justify-content-center">
            <img src="{{ central_image }}" class="col-xs-2 centralImage"/>
        </div>
        <div class="row justify-content-center">
            {% for link in links %}
                <a class="centralLinks col-lg-2" href="{{ url_for( link.link ) }}">{{ link.display }}</a>
            {% endfor %}
        </div>
    </div>
  </body>

{% endblock %}

app/templates/projects.html
{% extends 'publications.html' %}

app/templates/publications.html
{% extends 'base.html' %}

{% block site_content %}
  {% block styles %}
    {{ super() }}
    <!-- Custom styles for this template -->
    <link href="static/custom_research_responsive.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=UnifrakturMaguntia" />

  {% endblock %}
  <body>
  <h1>{{ title }}</h1>
    <div class="container">
      <div class="row">
          <div class="col-xs-6 justify-content-center">
              {{ blurb }}
          </div>
      </div>
      {% for paper in papers %}
          <div class="row">
              <a class="paperTitle col-xs-6" href="{{ paper_config[paper.title].content_path }}"> <h5>{{ paper.title }}</h5> </a>
          </div>
          {% if paper_config[paper.title].coauthors %}
          <div class="row">
              <p class="coauthors">with {{ paper_config[paper.title].coauthors }}</p>
          </div>
          {% else %}
          <p></p>
          {% endif %}
          <div class="row">
              <h6>Abstract</h6>
                <div>{{ paper_config[paper.title].abstract }}</div>
          </div>
      {% endfor %}
    </div>
  </body>
{% endblock %}